### ISSUE TITLE
Passwords in all the things

### ISSUE THREAD

**Issue by KeiroD** [hackmods/Script-Depot#1]
Really? You left passwords in your scripts? There's quite a few like this, such as [this](https://raw.githubusercontent.com/hackmods/Script-Depot/master/sh/ChunkhostVPSsetup.sh)... I hope those were changed after you wrote these?

**Comment by bradgillap** [comment]
None of these passwords were used in production environments. What you are seeing are placeholders.

**Comment by hackmods** [comment]
Thanks brad, all passwords are replaced with generated passwords, thank you for notifying us though!
